"""Publish the bundled Skillogy graph when its build artifact changes.

The graph dump is generated by our builder, not supplied by an API caller.
Applying it and the release marker in one Neo4j transaction keeps readers on
the previous committed catalog until the complete new graph is available.
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass

from decepticon.skillogy.server.neo4j_backend import Neo4jBackend

log = logging.getLogger(__name__)

_OWNER = "decepticon-bundle"
_CATALOG = "bundled"
# Legacy checked-in dumps were built with --frozen-built-at. An out-of-band
# custom dump using the same provenance is indistinguishable from the bundle;
# unmatched records are archived under a separate label rather than deleted.
_LEGACY_BUILT_AT = "1970-01-01T00:00:00+00:00"
_SKILL_PREFIX = "MERGE (n:Skill {"
_EDGE_PREFIX = "MATCH (a:Skill {"


@dataclass(frozen=True)
class CatalogRelease:
    digest: str
    statements: tuple[str, ...]
    skill_count: int

    @classmethod
    def from_cypher(cls, text: str) -> CatalogRelease:
        statements = tuple(
            statement.strip().rstrip(";").rstrip()
            for statement in text.split(";\n")
            if statement.strip()
        )
        skill_count = sum(statement.startswith(_SKILL_PREFIX) for statement in statements)
        if not statements or not skill_count:
            raise ValueError("bundled catalog has no Skill nodes; refusing to publish")
        return cls(hashlib.sha256(text.encode("utf-8")).hexdigest(), statements, skill_count)


def _owned_statement(statement: str) -> str:
    """Tag only builder-emitted Skill nodes and their outgoing relationships."""
    if statement.startswith(_SKILL_PREFIX):
        if "\nSET " not in statement:
            raise ValueError("builder Skill statement has no SET clause")
        return (
            statement + ", n.catalog_owner = $catalog_owner, n.catalog_release = $catalog_release"
        )
    if statement.startswith(_EDGE_PREFIX):
        if "\nSET " in statement:
            return (
                statement
                + ", r.catalog_owner = $catalog_owner, r.catalog_release = $catalog_release"
            )
        return (
            statement
            + "\nSET r.catalog_owner = $catalog_owner, r.catalog_release = $catalog_release"
        )
    return statement


def reconcile_bundled_catalog(backend: Neo4jBackend, release: CatalogRelease) -> bool:
    """Return True if a changed release was published, False if already current.

    The release marker is locked before any graph mutation. A second replica
    waits on that lock and checks the committed digest, avoiding duplicate work.
    Unowned custom records are preserved unless they share the frozen builder
    provenance used by old bundled dumps; unmatched records with that exact
    provenance are archived on the first managed release. Later releases only
    clean up records explicitly marked as bundle-owned.
    """
    with backend._driver.session(database=backend._database) as session:
        current = session.run(
            "MATCH (c:SkillogyCatalog {name: $name}) RETURN c.digest AS digest",
            name=_CATALOG,
        ).single()
        if current is not None and current["digest"] == release.digest:
            return False
        # Without a unique key, two first-boot replicas can each MERGE a new
        # marker and publish independently. Neo4j serializes MERGE of the
        # constrained key even before either replica has committed a marker.
        session.run(
            "CREATE CONSTRAINT skillogy_catalog_name IF NOT EXISTS "
            "FOR (c:SkillogyCatalog) REQUIRE c.name IS UNIQUE"
        ).consume()
        with session.begin_transaction(timeout=600) as tx:
            row = tx.run(
                "MERGE (c:SkillogyCatalog {name: $name}) "
                "SET c.locked_at = datetime() RETURN c.digest AS digest",
                name=_CATALOG,
            ).single()
            if row is not None and row["digest"] == release.digest:
                tx.rollback()
                return False
            first_managed_release = row is None or row["digest"] is None

            for statement in release.statements:
                tx.run(
                    _owned_statement(statement),
                    catalog_owner=_OWNER,
                    catalog_release=release.digest,
                ).consume()

            row = tx.run(
                "MATCH (s:Skill {catalog_owner: $owner, catalog_release: $release}) "
                "RETURN count(s) AS skill_count",
                owner=_OWNER,
                release=release.digest,
            ).single()
            actual = 0 if row is None else int(row["skill_count"])
            if actual != release.skill_count:
                raise RuntimeError(
                    f"catalog verification failed: expected {release.skill_count} skills, found {actual}"
                )

            if first_managed_release:
                # The checked-in legacy builder dump stamped bundled skills
                # with a frozen timestamp and empty commit SHA. Current nodes
                # were tagged above, so the remaining matching nodes are
                # presumed obsolete. Archive instead of deleting because a
                # custom import can share the same builder provenance.
                tx.run(
                    "MATCH (s:Skill) WHERE s.catalog_owner IS NULL "
                    "AND s.built_at = $built_at AND s.commit_sha = '' "
                    "AND s.path STARTS WITH '/skills/' "
                    "SET s:SkillogyLegacySkill, s.catalog_archive_reason = 'superseded bundle' "
                    "REMOVE s:Skill",
                    built_at=_LEGACY_BUILT_AT,
                ).consume()
                # Legacy builder relationships had no ownership marker. Only
                # run this adoption cleanup once; later user-added unowned
                # relationships are preserved on future catalog updates.
                tx.run(
                    "MATCH (s:Skill {catalog_owner: $owner})-[r]->() "
                    "WHERE type(r) IN ['IN_PHASE', 'TAGGED', 'IMPLEMENTS', 'BELONGS_TO'] "
                    "AND r.catalog_owner IS NULL DELETE r",
                    owner=_OWNER,
                ).consume()
            tx.run(
                "MATCH (s:Skill {catalog_owner: $owner}) "
                "WHERE s.catalog_release <> $release DETACH DELETE s",
                owner=_OWNER,
                release=release.digest,
            ).consume()
            tx.run(
                "MATCH (:Skill {catalog_owner: $owner})-[r]->() "
                "WHERE r.catalog_owner = $owner AND r.catalog_release <> $release DELETE r",
                owner=_OWNER,
                release=release.digest,
            ).consume()
            tx.run(
                "MATCH (c:SkillogyCatalog {name: $name}) "
                "SET c.digest = $release, c.skill_count = $skill_count, "
                "c.published_at = datetime() REMOVE c.locked_at",
                name=_CATALOG,
                release=release.digest,
                skill_count=release.skill_count,
            ).consume()
            tx.commit()
    log.info(
        "published bundled Skillogy catalog %s with %d skills",
        release.digest[:12],
        release.skill_count,
    )
    return True
